version: "3.8"

services:
  mongo:
    image: mongo
    container_name: ms-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      -  5672:5672
      -  15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  mongodbdata:
  